### ISSUE TITLE
data flow visualization

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#102]
@rachelshekar commented on [Thu Mar 02 2017](https://github.com/terraref/computing-pipeline/issues/277)

use yesworkflow for documentation
tracks providence

do not need high level of detail - detail in google sheet is appropriate.

@dlebauer to talk to Bertram

**Comment by rachelshekar** [comment]
This was explored in https://github.com/terraref/reference-data/issues/77

**Comment by rachelshekar** [comment]
@dlebauer can this be closed?
