### ISSUE TITLE
Review storage of Reflectance Indices in BETYdb and mappings to netCDF metadata

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#105]
Following #72 we have created a number of records in the variables table to define Reflectance Indices based on definitions in the Index Database (indexdatabase.de)

#### Storage in BETYdb

There is currently  a lot of redundant information to clean up - mostly the same information persisting across fields

![image](https://cloud.githubusercontent.com/assets/464871/23970346/690e3646-0997-11e7-8629-95bab9d5055b.png)

These values can be queried via
* API: https://terraref.ncsa.illinois.edu/bety/api/beta/variables?key=9999999999999999999999999999999999999999&limit=none&type=~Reflectance+index
* SQL: `select * from variables where type = 'Reflectance Index';`

How can we best use the fields in this table as well as the methods table?

We should retain:

* some field that uniquely identifies a row in the index database
  * 'label' field matches records in the [Index Databaswe](http://www.indexdatabase.de/db/i.php) (can be accessed with R client [ridb](https://github.com/ropenscilabs/ridb))
   * which would be the most field to link with the index database? (originally it was 'standard name' ... is that best?)
* citation information - perhaps this could be linked via the methods table?
* equation - also in the methods table (description?)
* distinction of indices with same name but different equations
* distinquish indices computed with same equation but different sensors

We should also have meaningful min/max that will capture clear outliers (e.g. could NDVI max be reduced from infinity to 10? to 100?)

#### Mapping to metadata in netCDF files

In https://github.com/terraref/extractors-hyperspectral/pull/20

I am proposing the following mappings from BETYdb to netCDF (current draft of netcdf reflectance index data product):

|BETYdb | netCDF | 
|:---|:---|
| name | name | 
|standard_name | standard_name|
|description | description|
|label | long_name|
|units| units |

Are there any other fields that should be included? Explicit links to records in BETYdb, indexdatabase.de, or references?

### Completion Criteria

* [x] review the use of different fields
   * are we using the fields appropriately?
   * is there a better way to generate standard names? Currently they may contain specific bands and / or authors
   * [x] Please make comments on this [**google spreadsheet**](https://docs.google.com/spreadsheets/d/1T8cI7wbHj_X2n1bQQmQAVVnf9wD2Y2UB_cqhyMtBeRA/edit#gid=0)
* [x] check that min and max values are sensible. 
   * can we further constrain these based on the range of what should be observable at the earth's surface?
* [x] What information should we deconvolve. Many fields have repeated info. And in many cases, the citations and equations in the 'description' should be linked as 'methods'.  
   * are there any cases where an index computed using different equations should have the same variable but different methods?
   * a case for the same variable name and different methods would be the same equation and citation but different sensors
* [x] update variables and methods tables as appropriate following above review (@remotesensinglab)

**Comment by ashiklom** [comment]
Re: consrtaint -- Anything involving division by a reflectance value can have an upper bound of infinity, since I think it's possible to observe reflectance values below an instrumental detection limit. It may make sense to add "typical_max" and "typical_min" fields that can be easily used to flag bad values.

**Comment by ashiklom** [comment]
I added some comments to the Google doc. Let me know if you have any questions.

**Comment by dlebauer** [comment]
@ac-gl-chris and @remotesensinglab could you please review this?

**Comment by dlebauer** [comment]
@ac-gl-chris could you please add definitions of new indices to that table, using names and definitions from indexdatabase.de where they exist?

**Comment by ac-gl-chris** [comment]
@dlebauer do you mean [this table](https://github.com/terraref/documentation/blob/master/spectral_indices.md)

**Comment by dlebauer** [comment]
No, see the Google spreadsheet linked to above

**Comment by ac-gl-chris** [comment]
I added the meta data to the spreadsheet. 
IDs are missing since I haven't found any and the min/max values are only filled by what I found [here](http://www.harrisgeospatial.com/docs/VegetationIndices.html)

**Comment by remotesensinglab** [comment]
I am still reviewing it. Thanks

**Comment by dlebauer** [comment]
I've inserted these into the database. If further changes are needed, we can update there. Many of the min/max values could be constrained to something more realistic (many ranges are currently set to +/-Infinity, -1, 1 for normalized differences, or 0, Infinity for ratios).

Here are the insert statements: https://gist.github.com/dlebauer/0e50afea0bc0d89b4d8a263866144c14

Here are the results: https://terraref.ncsa.illinois.edu/bety/api/beta/variables?key=9999999999999999999999999999999999999999&limit=none&type=%7EReflectance+index
