### ISSUE TITLE
Data package for publication

### ISSUE THREAD

**Issue by craig-willis** [terraref/reference-data#106]
This task was created based on discussions from #24. 

Implement data package(s) for TERRA-REF according to Nature Scientific Data requirements, for publication in Dryad or similar repository.  See [design notes](https://docs.google.com/document/d/1bwx9uWRMfft7uR_IBGkJja9dZO-Uan_5fbikz5N6Eyw/edit#heading=h.p7q8xuvex69e) for specific requirements.  In short, define the package contents, DataCite metadata, and data management policy.

Completion criteria:
* [ ] [Requirements](https://docs.google.com/document/d/1bwx9uWRMfft7uR_IBGkJja9dZO-Uan_5fbikz5N6Eyw/edit#heading=h.p7q8xuvex69e)
* [ ] Implement data package
* [ ] Implement DataCite metadata
* [ ] Define data management policy
* [ ] Stakeholder review
* [ ] Deposit with Dryad (work with curator)

**Comment by craig-willis** [comment]
Had an email exchange with Dryad curator and it sounds like they are open to us depositing the data package as described.  I will put together a preliminary package for v0 and work with them to deposit.

**Comment by craig-willis** [comment]
Per discussions with Rob, will use Clowder API to generate data package. Still a work in progress.

**Comment by max-zilla** [comment]
@craig-willis do you still have a contact at Dryad you can share with me, or should I start anew?

**Comment by craig-willis** [comment]
I've forwarded the exchange I had with the then-curator.  I know that Dryad is in the middle of a major re-launch since partnering with CDL last year. I she is still involved although not in the same role.

**Comment by dlebauer** [comment]
this is done: staged in google drive for deposition at Dryad - can open new issues as necessary
