### ISSUE TITLE
Update websites with link to alpha user signup application

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#107]
Update each of the websites with the following text

"Data are currently available for alpha user testing. For access, please [apply to our alpha user program](https://goo.gl/forms/eYrhvMBj48haloni2)"

* [x] terraref.ncsa.illinois.edu/bety ( @gsrohde )
* [x] terraref.ndslabs.org ( @craig-willis )
* [x] terraref.ncsa.illinois.edu/clowder

**Comment by craig-willis** [comment]
I'm the last one -- added to Workbench and closing.
