### ISSUE TITLE
Sensor metadata should be public

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#108]
Currently, sensor metadata are public, but require login to view collections because they are in a private space.

### Completion Criteria   

* [x] Reorganize sensor metadata so that they are publicly available
* [ ] All links to metadata collections in documentation work

**Comment by max-zilla** [comment]
I created a new public space and put pointers to these in there. The datasets were already accessible but Clowder doesn't currently support collection-level public checks so this is the most straightforward solution.

This did not change any links - @craig-willis do you know if we still need to check the documentation links, or is that something you did?

**Comment by craig-willis** [comment]
Links are still working. Closing this.
