### ISSUE TITLE
error in height of 1100 cm 

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#128]
This measurement of panicle_height is 1100 cm, which is an obvious typo. 

In cell AD399 the [spreadsheet](https://terraref.ncsa.illinois.edu/bety/traits/6000091243) it was recorded as 1098 cm and rounded to 3 significant digits when it was uploaded. 

@NewcombMaria can you please check this value? Was it transcribed from field notes?

* I have flagged it as incorrect in the database. `update traits set checked = -1 where id = 6000091243;`

If you can find the correct value, please 

* [x] change the value in the database https://terraref.ncsa.illinois.edu/bety/traits/6000091243/edit 
* [x] mark the value as checked (one of these) https://terraref.ncsa.illinois.edu/bety/traits?utf8=%E2%9C%93&DataTables_Table_0_length=25&search=MAC+Field+Scanner+Season+2+Range+25+Pass+7&direction=&sort=

Otherwise, feel free to close the issue and we can leave it flagged as incorrect.

**Comment by NewcombMaria** [comment]
Thanks @dlebauer for catching the typo.  The value should be 98 cm.  I corrected it in the spreadsheet and in the database.
