### ISSUE TITLE
remove empty scanner3DTop directories

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#133]
between 2017-05-26 00:00:00 and 2017-06-01 07:20:00 (Arizona time GMT-7) the scanner3DTop was running but not generating any data files (only directories and json files).

These should be deleted. I think this will work but please confirm! Note: there are some .png files generated during debugging around 7:20 AM. Anything before noon can be deleted.

```sh
rm -rf terraref/sites/ua-mac/raw_data/scanner3DTop/2017-05-2[6789]/*
rm -rf terraref/sites/ua-mac/raw_data/scanner3DTop/2017-05-3[01]/*
rm -rf terraref/sites/ua-mac/raw_data/scanner3DTop/2017-06-01/2017-0*
```

**Comment by jdmaloney** [comment]
That looked good, I went ahead and ran the deletes.  All cleaned up.
