### ISSUE TITLE
Get Feedback on Prototype Flask App

### ISSUE THREAD

**Issue by nickheyek** [terraref/reference-data#139]
### Description
To gain insight helpful for designing the Shiny app, feedback will be collected on the prototype Flask App by using a Google form.

### Completion Criteria
- [x] Create Google form to learn about how Shiny app can on Flask app prototype
- [x] Send out Google form to TERRA-REF team
- [x] Gain feedback to incorporate into design of Flask app

**Comment by dlebauer** [comment]
Feedback was given via this google form https://docs.google.com/a/illinois.edu/forms/d/12lyS4vy_CNBdlhRwkAk4hnyu0SOI0aW8PFCfQIoLWBI/edit#responses

Key points:
* heat map
* subset by plot / genotype

Will be addressed in future issues
