### ISSUE TITLE
Create Basic Visualizations for Traits within a Given Season (Partial Data)

### ISSUE THREAD

**Issue by nickheyek** [terraref/reference-data#143]
### Description
App should support viewing data from multiple seasons to choose from select menu, and should allow viewing of data for specific variables. Visualizations at this point will be basic scatter plots and will be working with only partial data due to speed constraints.

### Completion Criteria
- [x] Write code to access traits from various experiments
- [x] Create scatter-plots for each variable in a given season

**Comment by dlebauer** [comment]
implemented by #168
