### ISSUE TITLE
Deploy Shiny App

### ISSUE THREAD

**Issue by nickheyek** [terraref/reference-data#145]
### Description
The Shiny app will be deployed so that it can be viewed from a public domain.

### Completion Criteria
- [ ] Incorporate R Studio Shiny Server functionality into app
- [ ] Discuss options for deploying Shiny app
- [ ] Deploy Shiny app to a public URL

**Comment by dlebauer** [comment]
Can prob. start w/ rocker/shiny docker container: https://hub.docker.com/r/rocker/shiny/

**Comment by dlebauer** [comment]
See Dockerfile started in https://github.com/terraref/traitvis-webapp and notes on use in the [repository's README](https://github.com/terraref/traitvis-webapp#docker-notes)

**Comment by dlebauer** [comment]
Many of the dependencies will be in this container: https://github.com/rocker-org/geospatial/blob/master/3.3.1/Dockerfile

* revert to exposing environment variables as in that file
  * you can develop using the ssh tunnel, and the only thing that may need to change for deployment is the betydb host
* add the packages listed in the README

**Comment by dlebauer** [comment]
deployed here: http://traitvis.terraref.ndslabs.org/
