### ISSUE TITLE
Implement Subsetting by Cultivar/Genotype

### ISSUE THREAD

**Issue by nickheyek** [terraref/reference-data#154]
### Description
Implement option for user to view data from whole field (box plots w/ all data points), or by specific cultivar (line plot).

### Completion Criteria
- [x] Parse API data to extract unique cultivar ids, render select menu from them
- [x] Render line plot upon selection of specific cultivar id

**Comment by dlebauer** [comment]
Depends on https://github.com/terraref/reference-data/issues/135

**Comment by dlebauer** [comment]
implemented by #168
