### ISSUE TITLE
Define expertise of current committeemembers

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#17]
This will help understand who can help where, and what we need to fill in.
* [x] create a google form to let people check boxes (or select expertise levels 1-5) as well as provide free-form text responses
* [x] send to committee members 

* categories: remote sensing, image analysis, physiology, breeding, genomics, informatics, ... 
* levels: 0: never heard of it, 1: have heard of it but don't know, 2: have read the wikipedia page 3: could contribute to the wikipedia page (grad level) 4: use it as a tool actively in research 5: leader in field / expert in developing new methods

**Comment by rachelshekar** [comment]
See https://github.com/terraref/admin/issues/3

I suggest that you send this list to the committee before the meeting and ask for changes during the meeting

**Comment by davidlee2** [comment]
At the moment I’m trying to pin down a couple more TERRA individuals about having the next call the afternoon of the 28th or 30th.

**Comment by dlebauer** [comment]
The table of participant expertise is here: https://docs.google.com/spreadsheets/d/14Z-Y2MmVy94X561VJdecBSu577VQ4H6G65gh8p_pkD4/edit?usp=sharing and has been shared with the group
