### ISSUE TITLE
Update list of .nc files daily for thredds server

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#171]
currently the thredds server requires a list of .nc files that is parsed to an xml catalog used by the THREDDS server at https://terraref.ncsa.illinois.edu/thredds/catalog.html

However, the file has not been updated since July 17. This should be updated daily, prior to the generation of the xml file (should these be done in sequence in the same script?) 

Assigned to @jdmaloney; tagging @robkooper

**Comment by jdmaloney** [comment]
@dlebauer @robkooper Cron job now in place to update this every day at 11:58pm (though I just did it once by hand).  Output for Rob kept in /gpfs/largeblockFS/projects/arpae/terraref/sites/ua-mac/Level_1/hyperspectral/nc_files

**Comment by jdmaloney** [comment]
This is all working now on a daily basis

**Comment by dlebauer** [comment]
I am not sure if anything changed, but now the directory tree in the UI provides no information about which files will be found at each of the links called 'project'. 

I suspect this may be a bug - did you change the script, and is there a way to replicate the directory structure on roger?

This is how it currently looks:

![image](https://user-images.githubusercontent.com/464871/29680270-ad4da89e-88c9-11e7-9421-e00e3c95ac8e.png)

But it would be great if it looked more like

> | ua-mac
| | hyperspectral
| |  |-2017-01-30
| |  |  |-2017-01-30__14-49-10-193
| |  |  |-2017-01-30__15-53-50-679
| |  |  |-2017-01-30__15-02-21-574

**Comment by robkooper** [comment]
fixed, format had changed of the file listing.

now is:

![image](https://user-images.githubusercontent.com/1580696/29681683-1b8cded4-88ce-11e7-831b-74c9fc3fdc3c.png)
