### ISSUE TITLE
Give Roger access to beta testers

### ISSUE THREAD

**Issue by rachelshekar** [terraref/reference-data#21]
Noah Fahlgren, Rob Pless at WUSTL and Charlie Zender

Include sample data

Private owncloud server?

**Comment by yanliu-chn** [comment]
the ldap groups they should be assigned to: prj_cg_users and prj_cg_arpae

**Comment by yanliu-chn** [comment]
If they don't have ncsa account, please let me know their email addresses. i can contact them to create sponsored guest forms.

**Comment by dlebauer** [comment]
@yanliu-chn email addresses and github usernames are

| name | email | github |
|----|----|----|
| Charlie Zender | zender_at_uci.edu | @czender |
| Noah Fahlgren | nfahlgren_at_danforthcenter.org | @nfahlgren |
| Robert Pless | pless_at_wustl.edu |  |

**Comment by dlebauer** [comment]
This issue was moved to terraref/computing-pipeline#71
