### ISSUE TITLE
Query sensor data file path using terrautils

### ISSUE THREAD

**Issue by Paheding** [terraref/reference-data#219]
_Summary_: The general purpose is to use _terrautils.products_ to query the file path for given sensor name and site name, so that we can link the site locations between images and field measurements.  Current functions _terrautils.products_ can successfully return file path for sensor name 'Thermal IR GeoTIFFs Datasets' but did not work for 'RGB GeoTIFFs Datasets' and maybe others, so the question is that whether we do not have data for given sensor name and site name or is there other reasons.  Can we find out the problem and improve the associated function to address this issue? 

**Here is one of the examples error:** 
sensor = 'RGB GeoTIFFs Datasets'
sitename = 'MAC Field Scanner Season 1 Field Plot 515'

**Error**
Traceback (most recent call last):
datasets = get_file_listing(None, url, key, sensor, sitename)
stream_id = r[0]['id']
KeyError: 0

### Completion Criteria 

* [ ] Identify source of bug
* [ ] resolve problem (error does not occur)
* [ ] Write tests to ensure it doesn't happen again.

**Comment by max-zilla** [comment]
@jterstriep in the error above we just don't have a stream RGB GeoTIFFs Datasets for the 'MAC Field Scanner Season 1 Field Plot 515' plot, but we aren't catching that.

it works for valid plots in later seasons:
```
>>> from terrautils.products import get_file_listing
>>> l = get_file_listing(None, "http://terraref.ncsa.illinois.edu/clowder/", "Pb3AUSqnUw", "RGB GeoTIFFs Datasets", "MAC Field Scanner Season 4 Range 26 Column 6")
>>> len(l)
5
>>> l[0]
{u'contentType': u'image/tiff', u'filepath': u'/home/clowder/sites/ua-mac/Level_1/rgb_geotiff/2017-07-03/2017-07-03__11-48-50-648/rgb_geotiff_L1_ua-mac_2017-07-03__11-48-50-648_right.tif', u'filename': u'rgb_geotiff_L1_ua-mac_2017-07-03__11-48-50-648_right.tif', u'date-created': u'Wed Nov 01 09:52:32 CDT 2017', u'id': u'59f9dfb04f0cfb5041110b98', u'size': u'24470750'}
```

**Comment by Paheding** [comment]
From [https://github.com/terraref/tutorials/blob/master/sensors/06-list-datasets-by-plot.md](url)
It looks like the currently available sensors are:

IR Surface Temperature
Thermal IR GeoTIFFs Datasets
flirIrCamera Datasets
(EL) sensor_weather_station
Irrigation Observations
Canopy Cover
Energy Farm Observations SE
(EL) sensor_par
scanner3DTop Datasets
Weather Observations
Energy Farm Observations NE
RGB GeoTIFFs Datasets
(EL) sensor_co2
stereoTop Datasets
Energy Farm Observations CEN

From the error we got I assume the dataset associated with sitename is limited for these available sensor, or maybe there is other reasons? 
Meanwhile, if  VNIR and SWIR sensor datasets could be included in this list would be very useful.

**Comment by max-zilla** [comment]
We need to add an explicit message to indicate if files are missing (e.g. some Season 1 RGB GeoTIFFs) so it's clear what's an error and what is unavailable.

either @jterstriep or I should implement in terrautils.

**Comment by max-zilla** [comment]
@Paheding pull request is here, if you are satisfied with it we can merge:
https://github.com/terraref/terrautils/pull/44

```
>>> from terrautils.products import get_file_listing

>>> l = get_file_listing(None, "http://terraref.ncsa.illinois.edu/clowder/", "KEY", "RGB GeoTIFFs Datasets", "'MAC Field Scanner Season 1 Field Plot 515'")

>>> l
[]
```

**Comment by Paheding** [comment]
@max-zilla This is great. Thanks. We can merge.
