### ISSUE TITLE
Handle new position information for NDVI and PRI

### ISSUE THREAD

**Issue by craig-willis** [terraref/reference-data#241]
NDVI and PRI are ready for new season, but we have new calibration and offset information.  We need to update the offsets in the sensor fixed metadata. There are no extractors for these sensors.

**Comment by max-zilla** [comment]
let's include this in:
https://github.com/terraref/sensor-metadata/pull/10/files

**Comment by max-zilla** [comment]
@craig-willis where are these new positions?

**Comment by max-zilla** [comment]
merged. followup in computing-pipeline#502
