### ISSUE TITLE
Environment logger Geostreams met data should be 5 min (not 5s) frequencies; netcdf should be available on thredds

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#242]
Per specification in https://github.com/terraref/computing-pipeline/issues/156#issuecomment-261286229 the geostreams met should have 5 min frequency. Currently the environment logger has 5 s frequency.

The high frequency data can be accessed in the environment logger netcdf files (@robkooper these should be available on the thredds server).

**Comment by robkooper** [comment]
What is the path for these files on disk, I can add them to the script to generate the thredds database.

**Comment by dlebauer** [comment]
Timestep fixed in https://github.com/terraref/computing-pipeline/issues/156#issuecomment-261286229 e.g. https://terraref.ncsa.illinois.edu/clowder/api/geostreams/datapoints?stream_id=46431&since=2017-01-02&until=2017-01-31

thredds no longer a priority
