### ISSUE TITLE
First-pass QC for 2017 scan for stomatal regulation campaign

### ISSUE THREAD

**Issue by NewcombMaria** [terraref/reference-data#243]
@max-zilla following up on the Tue telecon discussion on field campaigns, it would be great to be able to view a full-field overview of the 2017 scan that ran with the box raised high with larger FOV for purpose of being able to cover the field quickly for thermal data.  The name of the script file is 'StomatalRegulation_Sorghum4_ranges0.33m.cs'.  I don't know exactly which dates, but likely dates to check include: 
2017-06-16
2017-06-19
2017-06-21
This will help us with rough QC to determine if this scan could provide valuable data for this current season.

**Comment by max-zilla** [comment]
The higher resolutions for 06/21 are still being generated, but the thumbnail is complete and on disk under ua-mac/Level_1/fullfield/2017-06-21 (see stomatalregulation TIF).

![screen shot 2018-05-29 at 9 52 30 am](https://user-images.githubusercontent.com/14166971/40666777-2be55652-6326-11e8-87e9-3eb8fb6d11f6.png)

There are gaps between the photos. The higher resolutions might make this more obvious, but if we expected full coverage I will check the metadata to see whether the FOV field we use for georegistration actually reflects the larger value or not.

**Comment by max-zilla** [comment]
talked with @craig-willis about this. i was reminded that we store the camera FOV in fixed metadata in clowder as something that was not expected to change (like position in camera box, for example) so changed FOV settings, while they may be present in metadata.json files, are currently fetched from fixed md for processing. we will have to discuss refactoring pipeline to support variable FOV and reprocessing any days where this would've been changed.

**Comment by craig-willis** [comment]
@max-zilla Please create follow-up issue to address FOV problem and close this if possible.

**Comment by max-zilla** [comment]
Discussion has moved here: https://github.com/terraref/computing-pipeline/issues/456
