### ISSUE TITLE
R script to extract the 3d laser height estimates from Betydb

### ISSUE THREAD

**Issue by NewcombMaria** [terraref/reference-data#260]
@kimberlyh66  could you provide R script to extract a single day of 3d laser height estimates from Betydb from Season 5? Or could we set up a time for a demonstration of how to extract the sensor-derived height data from Betydb.  I have ground-truth height data from the end of Season 5 and @max-zilla suggested it would be useful to correlate the laser-derived heights with the ground-truth data.  @dlebauer suggested you could help with learning how to extract the data from Betydb.

**Comment by kimberlyh66** [comment]
@NewcombMaria an example R script that can be used to extract 3d laser height data from Betydb can be found at [https://gist.github.com/kimberlyh66/85dd71f23847a38520d60f781e1f60ba](https://gist.github.com/kimberlyh66/85dd71f23847a38520d60f781e1f60ba)

**Comment by NewcombMaria** [comment]
@max-zilla I was able to get help from Kimberly to run the R script to extract 3d-laser-derived heights from 31-March-2018.  There were only 37 mean height values and 24 were zeroes.  The sites were from a subset of plots in ranges 5, 6, 8, 12, 17, 18, 19, 20, 21, and one plot from 26.  Does this match with what you are seeing for outputs?  Manually collected height data is available from 30-March-2018 that could be compared to laser-derived data if we can pull together a full set of laser-derived data from that timeframe.

**Comment by dlebauer** [comment]
I can confirm that there are only 37 records in the database for March 31 2018. Not sure why this is the case unless either only a few ranges were scanned or the canopy height extractor wasn't run for all of the available data.

This is what we have:

![image](https://user-images.githubusercontent.com/464871/51866875-58055b00-2307-11e9-8b95-89d085b89440.png)
