### ISSUE TITLE
Review, revise, and complete experiment descriptions

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#275]
@NewcombMaria 

Please review and update the experiment descriptions and designs that we have in the database.

I've created a spreadsheet to make this easier. Please highlight any cells that you update.

https://docs.google.com/spreadsheets/d/1U2iA3N82G6ry4eGR_kliXzjI_e4PwkaGkmnQGMIQkP8/edit#gid=0

**Comment by NewcombMaria** [comment]
@dlebauer I've completed revisions and additions in the spreadsheet: 
https://docs.google.com/spreadsheets/d/1U2iA3N82G6ry4eGR_kliXzjI_e4PwkaGkmnQGMIQkP8/edit#gid=0

Cells with changes are highlighted - the majority have revisions or additions.

**Comment by dlebauer** [comment]
I've updated all of the records in BETYdb; sql statements are here https://gist.github.com/dlebauer/b7e5e3e6a4308afd16e77d126141dbed
