### ISSUE TITLE
BETYdb upload field measurements S9 South field

### ISSUE THREAD

**Issue by NewcombMaria** [terraref/reference-data#276]
@dlebauer and @Kimberly Huynh a couple 2019 S9 South field data sets are ready to be uploaded to Betydb.  I tried the bulk upload process and got an error about unresolvable site and treatment references.  Have culivars been linked to sites for S9 south field?  https://docs.google.com/spreadsheets/d/1s7AYUjDLiODpYgURCbjKSji00CLaj_Nw37qly-SrP6I/edit#gid=1200493486

**Comment by kimberlyh66** [comment]
@NewcombMaria cultivars have not been linked to season 9 sites. I will work on getting those linked and let you know when I finish.

**Comment by NewcombMaria** [comment]
@kimberlyh66  and @dlebauer are there still some steps that need to be taken for S9 field data uploads?  I tried again to upload the data set for South field final biomass but still get errors for unresolvable site references and treatment references.  

![S9_South_harvestdata_betydb_error](https://user-images.githubusercontent.com/22008637/65794643-71240d00-e11d-11e9-81c0-7a6b57c80a1c.PNG)

**Comment by dlebauer** [comment]
what are the warnings?

**Comment by NewcombMaria** [comment]
The warnings are only a list of columns that will be skipped, which is expected.

**Comment by NewcombMaria** [comment]
Hi @dlebauer and @kimberlyh66.  Any updates on this issue?  I'd like to follow through on the south field S9 upload for the 2 data sets either today or tomorrow if possible.

**Comment by dlebauer** [comment]
@NewcombMaria where is the data that you are trying to upload?

**Comment by NewcombMaria** [comment]
https://drive.google.com/drive/folders/1qqnCCFZWL14S-XhVN5ix0swWdkfUV4RB 
2 data sets as csv files

**Comment by dlebauer** [comment]
It looks like in the metadata Kimberly uploaded, plots were divided into east and west columns; in the data you are trying to upload it is not divided by E/W. Is that correct?

**Comment by NewcombMaria** [comment]
That's correct.  Both data sets are plot-level values (2-row plots).

**Comment by dlebauer** [comment]
@NewcombMaria I've fixed a few things - if you remove the string ' South Field' from your plot names, it should work.

**Comment by NewcombMaria** [comment]
Success!  I had to add a treatment called 'Border' for the buffer plots in between the 2 different irrigation levels.  Empty cells in the treatment column were not accepted.  The Season-9 south field biomass harvest data are uploaded along with a small subset of manual plant height estimates.

**Comment by dlebauer** [comment]
Fantastic! Can this issue be closed?

**Comment by NewcombMaria** [comment]
Yup, thanks
