### ISSUE TITLE
How to properly convert lemntec rawx format to generic hdr? 

### ISSUE THREAD

**Issue by parth-sankhavara** [terraref/reference-data#285]
I have rawx image files of lemnatec phenotyping. I need to convert back into hdr format. How could I?

**Comment by dlebauer** [comment]
@parth-sankhavara I don't think we have worked on that - we have hyperspectral cameras that generate hdr files. Where did you get these files?

**Comment by parth-sankhavara** [comment]
> @parth-sankhavara I don't think we have worked on that - we have hyperspectral cameras that generate hdr files. Where did you get these files?

@dlebauer No Problems, Btw, I have got that rawx files from lematec software.

**Comment by dlebauer** [comment]
got it - even though we use lemnatec hardware, they didn't provide any software for data processing - so we mostly start with whatever files the sensors generate and process from there, which is hdr in the case of the headwall sensors.
