### ISSUE TITLE
Fix invalid environmental_logger files

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#29]
Need to re-process existing environmental logger files per terraref/reference-data#26

* [x] rename to fix typo in name
* [x] convert to valid json
* [ ] move corrected files back to /projects/arpae/terraref/raw_data/ua-mac/EnvironmentLogger
* [ ] delete invalid, misnamed files 

something like:

```sh
for file in /projects/arpae/terraref/raw_data/ua-mac/EnvironmentLogger/*/*_enviromentlogger.json; 
do 
  cp $file $file.backup
  echo "[$(cat $file)]"  > $file
  sed -i 's/}{/},{/g' $file
  rename enviroment environment $file 
done
```

It may not be the most efficient, but it seems to work.

When everything checks out, we can `rm *.backup`

**Comment by dlebauer** [comment]
I've copied files to /gpfs_scratch/terra-rename/ and have submitted a job ([this script](https://gist.github.com/dlebauer/3eb6910b687209486b88f7c12110a370)) to process these files

**Comment by dlebauer** [comment]
Here is the code so far:

```sh
mkdir /gpfs_scratch/terra-rename
cp -R /projects/arpae/terraref/raw_data/ua-mac/EnvironmentLogger /gpfs_scratch/terra-rename/
for file in /gpfs_scratch/terra-rename/EnvironmentLogger/*/*_enviromentlogger.json
do    
    cp $file $file.backup
    echo "[$(cat $file)]"  > $file
    sed -i 's/}{/},{/g' $file
    rename enviroment environment $file
done
```

**Comment by dlebauer** [comment]
@yanliu-chn when PID 35213 is finished, could you please run the following (requires write access to `raw_data` folder)?

```sh
# move valid files as *.json
rsync -routi /gpfs_scratch/terra-rename/EnvironmentLogger/*/*environmentlogger.json \ 
     /projects/arpae/terraref/raw_data/ua-mac/
```

after everything is okay we can delete the scratch folder

```sh
# delete folder from scratch
rm -rf /gpfs_scratch/terra-rename
```

**Comment by TinoDornbusch** [comment]
Thanks for this workaround. We will fix this as soon as Markus is back on track from his sick leave.

**Comment by yanliu-chn** [comment]
Done except that I didn't remove the scratch data. Could anyone check if rsync was successful?

**Comment by dlebauer** [comment]
@yanliu-chn sorry, I gave you the wrong Rsync code ... 

1. [ ]  delete the previously moved *environmentlogger.json from /projects/arpae/terraref/raw_data/ua-mac/ (`rm /projects/arpae/terraref/raw_data/ua-mac/*.environmentlogger.json`)
2.  [ ] delete the misspelled original files `rm /projects/arpae/terraref/raw_data/ua-mac/EnvironmentLogger/*/*.enviromentlogger.json`
2.  [ ] move files from /gpfs_scratch/terra-rename/EnvironmentLogger/* to /projects/arpae/terraref/raw_data/ua-mac/EnvironmentLogger/

**Comment by yanliu-chn** [comment]
ok. i have rerun the rsync. but the `*/*environmentlogger.json` does not work because there are too many files to fit in a linux command. instead, i did the following. Please check to see if it worked as expected. It should work now.

<pre>
for f in /gpfs_scratch/terra-rename/EnvironmentLogger/*; do [ -d $f ] && echo "rsync -routi $f/*environmentlogger.json /projects/arpae/terraref/raw_data/ua-mac/EnvironmentLogger/`basename $f`/" >>/gpfs_scratch/arpae/logs/envjson-rsyn2.sh; done

chmod +x /gpfs_scratch/arpae/logs/envjson-rsyn2.sh

# on cg-hm02, do
/gpfs_scratch/arpae/logs/envjson-rsyn2.sh

</pre>

**Comment by rachelshekar** [comment]
@yanliu-chn - can this be closed?

**Comment by yanliu-chn** [comment]
if @dlebauer verified the results, it can be closed.
