### ISSUE TITLE
How to handle the different trait data of the same line?

### ISSUE THREAD

**Issue by liyawang** [terraref/reference-data#290]
I am trying to extract the Terra-REF trait data to run GWAS on biomass. So I extracted “aboveground_dry_biomass” but found that the values are quite different for the same line (see below).

	• write.table(biomass[,c('cultivar', 'mean', 'raw_date', 'units')], file="biomass.txt", sep="\t")
	• grep "PI156217" biomass.txt
		• "68"	"PI156217"	17810	"2017-09-12 00:00:00 -0500"	"kg / ha"
		• "732"	"PI156217"	30800	"2014-10-11 19:00:00 -0500"	"kg / ha"
		• "1877"	"PI156217"	15200	"2018-08-01 02:00:00 -0500"	"kg / ha"
		• "2094"	"PI156217"	23210	"2017-09-15 00:00:00 -0500"	"kg / ha"
		• "3854"	"PI156217"	8540	"2018-07-31 02:00:00 -0500"	"kg / ha”

Even for 2018, the values are 15200 vs 8540. I noticed that there are other biomass trait data. Do you think it is necessary to normalize these values to other traits or I can simply take the average for 2018? For GWAS, I need to compare traits against all BAP lines.

**Comment by dlebauer** [comment]
Hi Liya - thanks for your interest. Note that these results come from:

* three different years (2014, 2017, 2018), 
* two different locations (PeeDee research center in SC and Maricopa Ag Center in AZ )
   * (also note that the SC data are from [Brenton et al 2016](https://www.genetics.org/content/204/1/21), and aren't part of the TERRA REF data)
* two different treatments in 2017, one with drought treatment from Aug 1-14 and the other with drought treatment from Aug 15-30

Even then, it is surprising that the two values for 2018 are so different. @NewcombMaria can you confirm that these two measurements are correct?

For reference, I can access these results using the API: https://terraref.org/bety/api/v1/search?cultivar=PI156217&trait=aboveground_dry_biomass&key=YOURSECRETKEYHERE 
or database: `select sitename, city, cultivar, treatment, mean, raw_date, units from traits_and_yields_view where cultivar = 'PI156217' and trait = 'aboveground_dry_biomass';`

| sitename                                                 | city     | cultivar | treatment                                        | mean  | raw_date            | units   |
|----------------------------------------------------------|----------|----------|--------------------------------------------------|-------|---------------------|---------|
| MAC Field Scanner Season 4 Range 4 Column 7              | Maricopa | PI156217 | MAC Season 4: BAP water-deficit stress Aug 1-14  | 17810 | 2017-09-12 05:00:00 | kg / ha |
| Clemson University Pee Dee Research and Education Center | Florence | PI156217 | 2014 Clemson BAP Phenotyping Trials              | 30800 | 2014-10-12 00:00:00 | kg / ha |
| MAC Field Scanner Season 6 Range 34 Column 8             | Maricopa | PI156217 | MAC Season 6: Sorghum                            | 15200 | 2018-08-01 07:00:00 | kg / ha |
| MAC Field Scanner Season 4 Range 34 Column 10            | Maricopa | PI156217 | MAC Season 4: BAP water-deficit stress Aug 15-30 | 23210 | 2017-09-15 05:00:00 | kg / ha |
| MAC Field Scanner Season 6 Range 6 Column 10             | Maricopa | PI156217 | MAC Season 6: Sorghum                            | 8540  | 2018-07-31 07:00:00 | kg / ha |
