### ISSUE TITLE
Vocabularies / ontologies to support, and framework for linking synonyms

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#31]
Vocabularies to support and framework for relating synonyms across vocabularies, enable to search datasets with translation across vocabularies

Vocabularies to support:
- CGIAR sorghum ontology:
  - http://www.cropontology.org/ontology/CO_324/Sorghum%20ontology
  - http://www.cropontology.org/ontology/CO_715/Crop%20Research
- CF Standard name XML table http://cfconventions.org/Data/cf-standard-names/33/src/cf-standard-name-table.xml
- BETYdb variables https://www.betydb.org/variables.json
- ICASA Master Variable list

Related issues:
- terraref/reference-data#18
- terraref/reference-data#14

See also: 

EarthCube GeoSemantics project  
- Architecture: https://opensource.ncsa.illinois.edu/confluence/display/ECGS/Architecture
- Knowledge Integration Services http://ecgs.ncsa.illinois.edu/ 
  - KIS API: http://ecgs.ncsa.illinois.edu/KIS.html 

@lmarini

**Comment by craig-willis** [comment]
As per discussion with @dlebauer, for this task I'll focus on a system to support vocabulary mapping, initially focusing on the listed vocabularies/ontologies. I'll review existing solutions, particularly the EC Geosemantics server, and flesh out requirements. The basic requirement here appears to be a software-based solution and process for mapping these vocabularies where the resulting mapping can be leveraged by existing systems (e.g., BETYdb, cross-database search).

**Comment by craig-willis** [comment]
Spoke with IN-CORE project team at NCSA -- they have evaluated a number of vocabulary servers and seem to have closely aligned needs.  Will try to setup a meeting with ECGS and IN-CORE team in the coming week or so to share information and requirements.

**Comment by craig-willis** [comment]
I've been reviewing several services considered by the IN-CORE team for vocabulary management -- iQvoc, TemaTres, LOV, and Skosmos. I've also reached out to the Marine Metadata Interoperability (MMI) project about their ontology registry (http://mmisw.org/orr/). The MMI ORR was selected by the Earth Science Information Partners (ESIP) federation.  While MMI ORR is ontology-centric, it is designed specifically for the development of cross vocabulary/ontology mappings.

**Comment by craig-willis** [comment]
@JeffWhiteAZ @chporter @dlebauer 

We discussed one goal of this task as mapping the TERRAref output data and BETYdb to the ICASA vocabulary, possibly hosting a mapping service. Most of the services I've explored so far  (ECGS-KIS, MMI ORR, etc) rely on vocabularies or ontologies being represented in standard formats such as OWL or SKOS to take advantage of semantic mapping operations such as owl:sameAs, skos:exactMatch, etc. 

From my understanding, the ICASA master variable list is published as a Google spreadsheet. Do you know if there's been any discussion of publishing or rendering this in a more linked-data suitable format? If not, do you see any problems with us doing so for TERRA -- for example, writing an interface to the spreadsheet that publishes the variables via permanent URLs.

**Comment by JeffWhiteAZ** [comment]
Craig,
We have had several discussions about "ontologizing" the ICASA master variable list and as a first step, have considered publishing in a more readily viewed and searched format. That work hasn't moved ahead due to lack of funding. I expect Cheryl would support me in saying "yes" to any effort by TERRA to help us move in that direction. Thanks for the offer.
What sort of effort would this require? What approach would you suggest beyond what you outline above?

**Comment by craig-willis** [comment]
Thank you, Jeff. Now that I know you're open to it, I'll put together a few options for discussion this week.

**Comment by nfahlgren** [comment]
@craig-willis @dlebauer I saw the note about a standard/interchange format for PlantCV, do we want to have that discussion here or a separate issue?

**Comment by craig-willis** [comment]
@nfahlgren I think #18 is the right forum for this.  I've added a Google Doc with a rough sketch of my thinking and welcome your feedback.

**Comment by craig-willis** [comment]
@JeffWhiteAZ @chporter @dlebauer 

I've added a (rough) document to the computing pipeline folder with some options for creating a linked-data suitable version of the ICASA model.

https://docs.google.com/document/d/1fTcTpKxcanPfRKPC-ZG8KjufGHscx5OCCB-5Ti58ARg/edit?usp=drive_web

Any feedback welcome.

**Comment by chporter** [comment]
@craig-willis 
This is a really nice framing of the issues involved in using the ICASA vocabulary for linked data. 
For what we are doing in AgMIP and DSSAT currently, the flat data dictionary is sufficient, but we understand the need for linked data and we want to support the efforts of groups that need that capability. We don't currently have resources to put a lot of effort into making that transition, but we welcome the opportunity to guide those efforts. Can we set up a call between Jeff, Cheryl, and Craig (and anyone else interested) to discuss where to go next?
For a while we had regular Skype calls with Celine Aubert, Elizabeth Arnaud, Medha Devare and others regarding the mapping of ICASA variables to the Crop Ontology and Agronomy Ontology. We may want to consider restarting that effort, including Craig Willis in the conversation.

**Comment by craig-willis** [comment]
Thank you, @chporter.  I'll bring this up in our weekly meeting tomorrow and report back.

**Comment by craig-willis** [comment]
@chporter @JeffWhiteAZ 
We discussed this at the meeting yesterday and do want to move forward with the effort to put together a RDF or similar version of the ICASA data dictionary and model -- the task will be assigned to me.  I'll setup a call to discuss. Thanks for your feedback.

**Comment by chporter** [comment]
@craig-willis @JeffWhiteAZ 
Glad to hear it, Craig.

**Comment by craig-willis** [comment]
Why is this closed? The related work is incomplete.

**Comment by max-zilla** [comment]
https://docs.google.com/spreadsheets/d/1FKSLTTIywQygRDv3nU6Xk6Z9D0xKxnoR_Mw1a8Kbjj0/edit?usp=sharing

**Comment by dlebauer** [comment]
Should we turn this into an epic, close, or ?

There are many subtasks associated with this.

**Comment by craig-willis** [comment]
Late response, but this should probably be an epic.

**Comment by dlebauer** [comment]
@craig-willis could you please update the milestone on this? turn it into an epic if necessary?
