### ISSUE TITLE
Document sensor calibration protocols

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#34]
From 2016-06-03 meeting, @LTBen offered to draft sensor calibration protocols, and would do this with help from @smarshall-bmr , @jeffwhiteAZ, @TinoDornbusch 

[Here is the list of sensors on google drive](https://docs.google.com/spreadsheets/d/1xkEHQd_5x3Yzv3f61bfns3ZFoP7xXq8AUNK4fmS3kXg/edit#gid=1085009115)

[Draft of Calibration Protocols](https://docs.google.com/document/d/18mfZXAyf3_e3tJHz6R2Gq_I8p_9qMJeF9noN_-9ymuw/edit#)

For each sensor, define:

* sensor name
* test object(s) / calibration panels
* method of calibration
* required experiments to validate the quality of calibration protocol

[Robinson and Biehl 1982 Calibration Procedures for Measurement of Reflectance Factor in Remote Sensing Field Research](https://github.com/terraref/reference-data/files/330332/biehl1982.pdf)

**Comment by JeffWhiteAZ** [comment]
From the Tuesday 8 June meeting at ALARC, field calibration of hyperspectral and FLIR are challenging and will require testing different options. We expect to pursue this during June-July and will hold meetings at ALARC to discuss progress.
I'd suggest Ben focus initially on protocols for:
RGB color component of StereoVIS
Stereo component of StereoVIS
3D Laser

**Comment by JeffWhiteAZ** [comment]
If there is pressure for an initial document, I would just ask Lemnatec (Ben) to provide their basic protocol.

**Comment by JeffWhiteAZ** [comment]
Now that  Lemantec has applied the calibration matrix to the 3D scanners, how can we best test how well the system is working? A first step would seem to be scan the aluminum target and determine how well the  measurements with calibrations applied compare to the measured dimensions of the target. 
This could easily be done while the field is clear. It would be interesting to try:
1. Different orientations of the target
2. Different scanning speeds
3. Night vs. day
I would expect to see X,Y,Z dimension accuracy expressed as RMSE or an equivalent indicator.

**Comment by solmazhajmohammadi** [comment]
@JeffWhiteAZ I am working on this. Staurt is going to do couple of test scans for me next week. Currently west 3D scanner is working perfectly, but East scanner needs some modification in the calibration file.

**Comment by rachelshekar** [comment]
See https://docs.google.com/spreadsheets/d/1xkEHQd_5x3Yzv3f61bfns3ZFoP7xXq8AUNK4fmS3kXg/edit#gid=194274492
