### ISSUE TITLE
Document the parts numbers and specifications for calibration panels / objects?

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#36]
We need to know the part numbers and specs for the calibration panels we are using. For example, SphereOptics says that for each panel 

> Calibration will be performed on a Perkin Elmer Lambda 19, data will be supplied electronically in 1 nm steps, 50 nm step printed documentation with NIST/PTB traceability with certificate for the range from 250 nm-2500 nm.

We need to collect this documentation. Please attach such documents to this issue.  

It will also be useful to have pictures of each panel made with a standard RGB camera.

| object | image | manufacturer | part number | comments |
| :-- | :-- | :-- | :-- | :-- |
| white reflectance panel | <img width="55" alt="screen shot 2016-06-17 at 1 42 51 pm" src="https://cloud.githubusercontent.com/assets/464871/16161117/723e77ac-3491-11e6-83c2-843ede376e2d.png"> | Spectralon | ? |  |
| munsel color chart | <img width="137" alt="screen shot 2016-06-17 at 1 42 29 pm" src="https://cloud.githubusercontent.com/assets/464871/16161121/764e6c94-3491-11e6-9532-227b174fac6d.png"> | ? | ? |  |
| 3D object | <img width="128" alt="screen shot 2016-06-17 at 1 41 46 pm" src="https://cloud.githubusercontent.com/assets/464871/16161126/7b62e64c-3491-11e6-96e7-484a5a8d0f39.png"> | ? | custom | made of solid aluminum with an accuracy of 0.1mm  and laser engraved checkboard pattern |
- are there any others?

**Comment by smarshall-bmr** [comment]
The white reflectance panel is made by SphereOptics. It is uncalibrated and carries only an I.D. number SG3156-U and has a 95% reflectance.

The color chart is manufactured by mennon. It is printed almost exclusively in Japanese, but it does have a key of the RGB values of all the color squares.

The 3D Object came with a set of labsphere Spectralon diffuse color standards Art 050-166. All 8 targets are individually labeled.

In addition we have a smaller 10x10cm SphereOptics uncalibrated target. I.D. SG3156-U and 95% reflectance.

I can enter all this information in a preferred location.

**Comment by dlebauer** [comment]
@smarshall-bmr 

What are the labels on the 8 targets. Are these calibrated?

It seems odd that we have calibration objects that aren't themselves calibrated - how will we use these if we don't know what their properties are?

For now, please put the information in a new worksheet here: https://docs.google.com/spreadsheets/d/1xkEHQd_5x3Yzv3f61bfns3ZFoP7xXq8AUNK4fmS3kXg/edit#gid=1085009115

And any documentation / calibration documents in a subfolder.

**Comment by smarshall-bmr** [comment]
It's common practice to use uncalibrated targets to quantify differences between runs. Calibrated targets are only used for initial calibration because they are both expensive and fragile. The uncalibrated target is measured on the calibration run and then further runs can be compared using the uncalibrated target without putting the calibrated standard target at risk through daily use.

Both the mennon color chart and 8 Spectralon diffuse color standards are calibrated. I am putting their full info in the google sheet that you linked.

**Comment by dlebauer** [comment]
Sounds like in the end we can calibrate our uncalibrated panels with sufficient precision, it just won't be certified by NIST.

**Comment by smarshall-bmr** [comment]
Using the calibrated color panels is more than enough to figure out the necessary correction curves for the colors we will be measuring, yes. The white panels that we have are still good for run to run color corrections too.

**Comment by dlebauer** [comment]
@craig-willis please make sure to capture this information in the sensor metadata

**Comment by smarshall-bmr** [comment]
I have uploaded the calibration certificates and spectral response csv files for the 8 diffuse color targets in Drive under TERRA-REF>Maricopa Expirements>field scanner operations>Sensor datasheets

**Comment by craig-willis** [comment]
Thank you,  @smarshall-bmr. 

For the record,  my plan is to organize the calibration target information in the same way as the sensor/device information in the Clowder Devices and Sensors collection:

https://terraref.ncsa.illinois.edu/clowder/collection/58035fa34f0c4a438cbb53dc

Each calibration object will be represented as a dataset with any associated images and documentation attached as files. Values that are needed programmatically -- such as the spectral response data -- will also be added directly to the dataset metadata.

**Comment by craig-willis** [comment]
@dlebauer 

What is the origin of https://github.com/terraref/reference-data/blob/master/Zenith%20LiteT%20Diffuse%20Reflectance%20Target%20-%2095%25R.csv?

I see "Zenith Polymer" (not LiteT) mentioned in the LemnaTec  sensor documentation for testing the VNIR. We have a calibration certificate for the Zenith Polymer (SG3051), but these don't match what was mentioned in the June comments above.

**Comment by dlebauer** [comment]
@craig-willis I am not sure - maybe @TinoDornbusch or @smarshall-bmr can provide some insight?

**Comment by rachelshekar** [comment]
@craig-willis  - can this be closed?

**Comment by craig-willis** [comment]
Yes. I think anything related should be opened as a new issue.
