### ISSUE TITLE
Add level to calibration test object 

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#37]
For consistent interpretation of calibration panels, Larry Biehl suggests making sure that the panel is level. 

Would it be feasible to attach a circular level [similar to this one](http://www.stahl-libellen.com/Circular_spirit_levels/Aluminium_transparent_28.html) to the test objects?

<img width="156" alt="screen shot 2016-06-17 at 2 05 20 pm" src="https://cloud.githubusercontent.com/assets/464871/16161746/d13c4308-3494-11e6-978e-4cce9b5b000a.png">

**Comment by smarshall-bmr** [comment]
Before each scan I have been checking the test object for levelness with a bubble level. A circular level would certainly make my job much easier though, as long as it can put up with the hot sun here. The 3D object gets scaldingly hot out in the sun!

**Comment by dlebauer** [comment]
@smarshall-bmr should this issue be closed? Can you get a circular level and attach it to the object(s)? Would be great to have these in the images.

**Comment by rachelshekar** [comment]
@smarshall-bmr ???

**Comment by rachelshekar** [comment]
@nshakoor - please talk to Stewart

**Comment by smarshall-bmr** [comment]
@dlebauer I can get a few bubble levels. Should we actually affix them to the calibration panels though?

**Comment by dlebauer** [comment]
Your choice- I think key is ability to put in the same place

**Comment by smarshall-bmr** [comment]
@dlebauer Would it be beneficial to have a level large enough that it shows up in imaging?

**Comment by dlebauer** [comment]
@smarshall-bmr I suspect anything larger than 2 cm will be sufficient if the imagers have mm resolution, correct?
