### ISSUE TITLE
Camera Position in metadata

### ISSUE THREAD

**Issue by solmazhajmohammadi** [terraref/reference-data#40]
Recorded camera location in camera box for some of the sensors (including SWIR) is not correct. Stuart is going to fix it.

**Comment by TinoDornbusch** [comment]
@smarshall-bmr  I thought that positions have been recorded correctly in Aachen. Well always doublecheck. 
How do you want to measure? I suggest to plumb down the center of view of each camera and measure relative to the plumbed down position of center box (0,0).

**Comment by solmazhajmohammadi** [comment]
@TinoDornbusch It might be just a typo, and reporting VNIR position instead of SWIR.

**Comment by smarshall-bmr** [comment]
@solmazhajmohammadi @TinoDornbusch I'll have a look this afternoon if the weather doesn't go downhill. Predictions aren't looking optimistic right now.

**Comment by solmazhajmohammadi** [comment]
@smarshall-bmr can you please update the issue... From which date you have applied the changes in metadada? Which one of the camera's location has been changed?

**Comment by dlebauer** [comment]
@smarshall-bmr I also created #42 which should make it easier to update the fixed sensor meta-data

**Comment by smarshall-bmr** [comment]
@solmazhajmohammadi @dlebauer would you prefer that the z-axis be the distance to the camera housing, distance to the lens, or distance to the actual detector? In the case of the SWIR there is a mirror that redirects the path of light so the effective imaging distance is quite a bit further away then the vis cameras even though their housings are relatively close in the z-axis.

**Comment by dlebauer** [comment]
The detector seems like the logical location but I will defer to Solmaz, Robert @pless, and others

**Comment by solmazhajmohammadi** [comment]
Distance to the detector and lens, both are logical. The principal point usually is inside the lens glass, distance to the lens might be a better option.

**Comment by dlebauer** [comment]
What is the "principal point"?

**Comment by solmazhajmohammadi** [comment]
It is the point that the focal length is measured from it.
