### ISSUE TITLE
Upload 2016 first season field measurements to BETYdb

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#46]
TERRA-Ref Maricopa Sorghum 2016 first season summary:
- Planting date:  April 19
- Harvest dates:  July 11-14
- Crop duration:  82 days post planting

Summary of manually-collected field measurements (ground truth data collection):
- [x] Emergence: compute percent emergence, n, and statistic
  - [x] Emergence seedling vigor, BAP:  7 dates
    -  [F13_2016_sorghum_emergence.csv](https://docs.google.com/spreadsheets/d/1zhyhAGOFJ-KXd_-kF_6kOeqh4NtppKbRwVHRk1cZzAk/edit#gid=23726065)
  - [x] Emergence final stand counts, all plots before thinning:  1 date
    - [F13_2016_sorghum_whole_field.csv ](https://docs.google.com/spreadsheets/d/1r_1aBeIlgROsWWhbH9B_Rc_3vDmqUej1TuhaRGuSwBQ/edit#gid=1350157961)
- [x] Plant height, all plots:  5 dates  (separate measurements for canopy and spike heights)
- [x] Node counts on 180 marked plants, 18 plots in BAP:  9 dates
- [x] Tiller counts on 180 marked plants, 18 plots in BAP:  6 dates
- [x] Phenology growth stage notes, all plots:  10 dates
- [x] Leaf desiccation ratings, all plots:  3 dates 
- [ ] Lodging and architectural leaning, all plots:  1 date
- [ ] Biomass samples in-season, 9 plots:  2 dates (includes leaf areas and moisture samples)
- [x] Radiation interception, BAP:  3 dates
- [ ] Porometer readings, 24 plots in BAP:  2 dates
- [ ] Harvest measurements, 597 plots plus 48 plots by row (645 plots, 694 subsamples):  
  - [ ] yield estimates 
  - [ ] moisture samples 
  - [ ] plant counts and row lengths for harvested sections of plots
- Raw data are in google drive (to be archived in Clowder)
- Code to process these data and prepare metadata are in the [`/scripts`](https://github.com/terraref/reference-data/tree/master/scripts) directory.

**Comment by rachelshekar** [comment]
@dlebauer - is this a priority for the V0 release?

**Comment by dlebauer** [comment]
@rachelshekar yes!

**Comment by rachelshekar** [comment]
associated with #61

**Comment by dlebauer** [comment]
@NewcombMaria what is the status of this?

**Comment by dlebauer** [comment]
@NewcombMaria status?

**Comment by NewcombMaria** [comment]
Trying to find time, and will make it high priority to make milestone by end of May 2017. Thanks

**Comment by rachelshekar** [comment]
redundant. see #61
