### ISSUE TITLE
Add geospatial metadata to hyperspectral metadata

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#47]
Currently the files only contain the start position. We don't have the width of the line and we don't have the location of each line. 

Presumably the gantry knows the x location where each line is triggered.

1. We need the bounding box for the field of view
2. We also need to know the x position of each line

Additional questions:

1. is the grid regular with x and y orthogonal? 
  * e.g. does x change within a line / does x depend on y and vice-versa? 
2. or could we start with bounding box and later reproject to rectangular grid

@solmazhajmohammadi and @FlyingWithJerome and @czender  please update / clarify / revise this issue 
@markus-radermacher-lemnatec suggestions?

**Comment by rachelshekar** [comment]
@dlebauer - can you assign this to someone?

**Comment by solmazhajmohammadi** [comment]
This could be combined with [Georeferencing hyperspectral data, issue #144](https://github.com/terraref/computing-pipeline/issues/144)

**Comment by dlebauer** [comment]
@solmazhajmohammadi closed as duplicate of #144
