### ISSUE TITLE
Halogen direct illumination spectrum

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#52]
Please provide a per-wavelength analysis of the light produced by the halogen lights in the sensor box. Columns would be wavelength and flux. 

Something like this (from http://www.cs.virginia.edu/~cab6fh/research/meetings/6_14_11/wikidown_6_13_11.html):

![image](https://cloud.githubusercontent.com/assets/464871/18715281/581b161c-7fde-11e6-9fb4-22ed7c4f2aef.png)

Presumably this should extend across the range of the VNIR and SWIR (~300-2500nm)

**Comment by TinoDornbusch** [comment]
@dlebauer Sorry I just saw this today. I add it to my ToDo list and send it asap.

**Comment by TinoDornbusch** [comment]
@dlebauer  We have no measured spectrum for the build-in halogen lamps Showtec 240V/75W. This information is also not available from the supplier.

We have a similar type measured Philips Twistline Halogen 230V 50W 18072. attached the spectrum.
[MeasurementPhilipsHalogenSpot.xlsx](https://github.com/terraref/reference-data/files/498197/MeasurementPhilipsHalogenSpot.xlsx)
