### ISSUE TITLE
MAC phenotractor documentation

### ISSUE THREAD

**Issue by max-zilla** [terraref/reference-data#62]
@craig-willis @dlebauer @rickw-ward @jtheun 

There was some email traffic recently regarding documentation of phenotractor data/metadata. Thought to start summarizing here. Relevant files:
https://terraref.ncsa.illinois.edu/clowder/collection/57d2cf2d4f0cf74155f89831

**Tractor sensor offsets**
![screen shot 2016-11-08 at 11 25 10 am](https://cloud.githubusercontent.com/assets/14166971/20109525/0e694924-a5a6-11e6-975c-c5aa7d4de5f3.png)

The 3rd sheet of the XLS file contains per-sensor offsets:
```
SENSOR NAME == (horizontal in meters, vertical in meters)
--------------------------
GPS == (0,0)
GreenSeeker == (1.111, -2.108)
IRT == (0.793, -2.981)
Ultrasoni == (0.508, -2.651)
```

"GPS coordinates of a particular sensor depend on the tractor GPS + MAC--> USDA correction + (sensor offset * tractor direction)" - David

"GPS outputs data in NAD83 UTM12N and I converted them to WGS84 UTM12N in order to overlay with your shapefile" - Matt

**Tractor data stream Table 1+2 field definitions**
Here are the two dictionaries extracted from the powerpoint and formatted as JSON - we can eventually use these as contexts for JSON-LD lookup.

**Table1** (e.g. F13_9-8-2016.Table1)
```
{
"TIMESTAMP": "TimeStamp – Date and time to the 1/5 of a second",
"RECORD": "Data logger record #",
"gpsTime": "time from  gga string",
"rmcTime": "time from the rmc string",
"latitude": "minutes (04 or 4)",
"latmin": "latmin = is fraction of minutes as a integer, convert by multiplying by 0.00000001 and add it to the 4 ",
"longitude": "longitude = first 3 digits degrees (111), 2nd 2 digits are minutes (58)",
"longmin": "fraction of minutes as an integer, convert by multiplying by 0.00000001 and add it to the 58",
"elev": "elevation of RTK antenna, in meters",
"qual": "quality:  4 = Fixed RTK , just for diagnostics",
"sats": "# satellites in use",
"hdop": "just for diagnostics",
"speed": "gps based speed of tractor, in knots",
"heading": "heading in degrees, in reference to true north",
"sonar(1)": "Port side ultrasonic displacement, mm",
"sonar(2)": "center ultrasonic displacement, mm",
"sonar(3)": "starboard row ultrasonic displacement, mm",
"IRT_1566": "Port row IRT, in degrees Celcius",
"IRT_1655": "Center row IRT, in degrees Celcius",
"IRT_1563": "Starboard row IRT, in degrees Celcius",
"SBT_1566": "sensor body temperature, port row sensor",
"SBT_1655": "sensor body temperature, center row sensor",
"SBT_1563": "sensor body temperature, starboard row sensor",
"mV1566": "raw millivolts measurement of thermopile, port sensor (in the case of recalibration) not needed under normal circumstances",
"mV1655": "raw mV measurement of thermopile, center sensor",
"mV1563": "raw mV measurement of thermopile, starboard sensor"
}
```

**Table2** (e.g. F13_9-8-2016.Table2)
```
{
"TIMESTAMP": "TimeStamp – Date and time to the 1/5 of a second",
"RECORD": "Data logger record #",
"starboardSensor": "Starboard GreenSeeker sensor serial #",
"starboardNDVI": "Starboard row NDVI value",
"centerSensor": "Center GreenSeeker sensor serial #",
"centerNDVI": "Center row NDVI value",
"portSensor": "Port GreenSeeker sensor serial #",
"portNDVI": "Port row NDVI value",
}
```

**PlantHeight.csv**
Lastly there is a PlantHeight.csv file with the following columns:
```
{
"Northing": "northing of sensor", 
"Easting": "easting of sensor",
"Plant Height": "calculated plant height",
"Sensor Elevation": "elevation of sensor",
"qual": "quality",
"sats": "# satellites in use",
"hdop": "just for diagnostics",
"speed": "gps based speed of tractor, in knots",
"heading": "heading in degrees, in reference to true north}"
```

"The files aren't perfect- there is GPS positioning misalignment issues at the north end of the field, where the gantry is parked- from driving a GPS under a giant hunk of steel." - John

Creating an issue on GitHub to start to corral some of the email traffic.

**Comment by dlebauer** [comment]
I've started a draft for the phenotractor here: https://github.com/terraref/documentation/blob/version1/user/protocols-tractor.md

@craig-willis where should this information in this issue go? Should the json bits go in https://github.com/terraref/sensor-metadata?
