### ISSUE TITLE
Review alpha user sign up form

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#69]
We are preparing a form for users who want to apply for early access to data. At the same time we are trying to get an idea of expected use cases. I would appreciate feedback on, e.g.

* are any questions too open ended?
* is there anything else we should ask?
* any of the existing questions that are too redundant / should not be asked?
* can we make it sound more friendly?
* any questions that need to be revised?

Please fill out the “alpha user” signup and provide feedback https://goo.gl/forms/7dpyUVtF4ZSl6iwy2

Feel free to edit the form here: https://docs.google.com/forms/d/1KG65Ai0WiS9yWAK56ChHFAf3bYgdNwObkUb2JPSr_QM/edit?c=0&w=1 (contact me if you need access; I have a copy of the first draft so don't worry)

**Comment by craig-willis** [comment]
A few comments:
* Consider linking to the data release policy on that first page
* Initial description could be clearer (set expectations for what's to come in the form -- I wasn't expecting the questionnaire).
* Better instructions for each question: why do you need my github username? Why do you need the data access information?
* Link to data products documentation, I might not know what I plan to use.
* A few minor typos (Whereever, "How do you want access our data?")

On a larger note, I think it might make sense to separate sign-up from survey/questionnaire.  Only include questions in the sign-up that will be used to approve.  Send a follow on questionnaire for information that would help improve the system. That said, maybe you'll get a higher response rate if you force the questions during sign up (or maybe fewer alpha users).

**Comment by rachelshekar** [comment]
I agree with Craig.  I can make updates tomorrow after we meet, @dlebauer
