### ISSUE TITLE
Top 3D Scanner Misalignment 

### ISSUE THREAD

**Issue by solmazhajmohammadi** [terraref/reference-data#70]
Physical position of the scanner has been changed (due to temperature change or wheel replacement). this  caused the misalignment between the heading_west and heading east pointclouds. 
Applying following transformation to the "Top-heading-west" pointcloud will fix it.

New offset:[-10  +42  0] 

I will write a script to compensate the offset.

**Comment by dlebauer** [comment]
@craig-willis is the sensor offset available in the meta-data, and if so, can we (should we) programmatically access it with related extractors? Can we assign dates for which this information is valid? What would be an appropriate protocol for updating metadata?

@solmazhajmohammadi can you work with Craig to generalize this solution?

**Comment by solmazhajmohammadi** [comment]
Sure,  
It has not been added to metadata yet. I'll ask Markus to add it to the metadata.
I am looking at the data to see when the misalignment occurred.

**Comment by dlebauer** [comment]
@solmazhajmohammadi I am not sure if the offset _needs_ to be in the file metadata. Even though the "sensor fixed metadata" is written with each image capture, I believe it should be stored somewhere like https://github.com/terraref/sensor-metadata/blob/master/sensors/scanner3D/sensor_fixed_metadata.json or in the geostreams sensor database; @craig-willis please advise

**Comment by craig-willis** [comment]
@solmazhajmohammadi @dlebauer 
I was under the assumption that the "sensor_fixed_metadata" written by LemnaTec would no longer be updated and that https://github.com/terraref/sensor-metadata repository will become the authoritative location for changes (which will be POSTed to the Clowder API). 

Maintaining this information in two places will be complicated.

**Comment by solmazhajmohammadi** [comment]
@craig-willis We haven’t added the offset to the metadata. you can update the sensor-metadata repository. 
@max-zilla I was not sure that if the code should go under the reference-data or computing pipeline, I uploaded the code here for now:
https://github.com/solmazhajmohammadi/3D_Misalignment

**Comment by craig-willis** [comment]
@solmazhajmohammadi  Sorry for the delay.  I've created ticket #74 to track my part of this. I'll let you know when complete.

**Comment by craig-willis** [comment]
@solmazhajmohammadi  Do you know the effective date of the change so I can add to the metadata?

**Comment by solmazhajmohammadi** [comment]
@craig-willis The effective date of the misalignment is November 22, 2016
Please update the offset to the following transformation, it fits better for the full row scan
[X Y Z]=[ -10  +42  0]

**Comment by craig-willis** [comment]
Thank you, @solmazhajmohammadi. Because "offset" is a little ambiguous, can you think of a more descriptive label for this -- something like "position correction offset"?

**Comment by solmazhajmohammadi** [comment]
"position correction offset" is OK. Here is some options:
- alignment correction offset
- post-calibration transformation

**Comment by rachelshekar** [comment]
@solmazhajmohammadi - can this issue be closed?

**Comment by solmazhajmohammadi** [comment]
No, we still need to apply the transformation to the dataset. 
The offset is hardcoded now, @craig-willis What is the label for this offset?

**Comment by rachelshekar** [comment]
@craig-willis and @solmazhajmohammadi - has this been completed?

**Comment by solmazhajmohammadi** [comment]
Final step depends on [Issue 44](https://github.com/terraref/reference-data/issues/44)

**Comment by rachelshekar** [comment]
scans being done next week to determine offset dependence on temperature; moving milestone

**Comment by solmazhajmohammadi** [comment]
The result is posted in #74
