### ISSUE TITLE
Curate UAV calibration information

### ISSUE THREAD

**Issue by craig-willis** [terraref/reference-data#73]
This tick tracks a specific subtask of https://github.com/terraref/computing-pipeline/issues/185

Completion criteria:
* [ ] UAV calibration documentation has been collected and organized in Clowder
* [ ] Documentation has been reviewed by relevant stakeholders

**Comment by rachelshekar** [comment]
@dlebauer can this be backlogged so @craig-willis can work on release-relevant issues?

**Comment by dlebauer** [comment]
info unavailable and not required to interpret calibrated UAV data
