### ISSUE TITLE
Add 3D Scanner offset to sensor metadata

### ISSUE THREAD

**Issue by craig-willis** [terraref/reference-data#74]
Subtask related to https://github.com/terraref/reference-data/issues/70. 

Completion criteria:
* [x] Offset information is stored in 3D scanner metadata
* [ ] Reviewed by relevant stakeholder

**Comment by rachelshekar** [comment]
The offset needs to be stored with the date.

**Comment by max-zilla** [comment]
3 values for offset - XYZ. No rotation or anything yet.

**Comment by ZongyangLi** [comment]
Another value needed if that's possible: unit for voxel in point cloud coordinate system.

**Comment by craig-willis** [comment]
@ZongyangLi Just to confirm, you're asking for a "unit" field with value "voxel" to be added to the 3d scanner metadata? How is this used?

**Comment by dlebauer** [comment]
Also, @ZongyangLi I thought that 'voxel' refers to the cubes that make up a regular array, and that this sensor generates a point cloud in which points have no volume and are not on a regular grid. Am I missing something?

**Comment by ZongyangLi** [comment]
@craig-willis @dlebauer 
Sorry for the confusion I have generated. When I say 'unit for voxel', I would like to know when point coordinate move from (0,0,0) to (1,1,1), how long is it in each direction in the field(real world). 

May be I am wrong, but to my understanding, a 3d scanner offset means an offset from point cloud coordinate system to gantry coordinate system.  When we have the 3d scanner offset and this 'unit transfer value', we are able to map every point to the field.

**Comment by dlebauer** [comment]
@ZongyangLi Now I understand ... I think the documentation section on ['geospatial information'](https://terraref.gitbooks.io/terraref-documentation/content/user/geospatial-information.html) has the transformations that you are looking for (if not, we can ping Yan).

**Comment by craig-willis** [comment]
Pull request:
https://github.com/terraref/sensor-metadata/pull/5

I've posted this to the clowder-dev instance for review:
https://terraref.ncsa.illinois.edu/clowder-dev/api/datasets/58920d9ae4b007e405e03301/metadata.jsonld

After PR is merged, I'll post to the primary clowder instance.

**Comment by craig-willis** [comment]
Assigning to Solmaz for review.

**Comment by solmazhajmohammadi** [comment]
@craig-willis Thanks for the update. The offset need to be applied to only one of the scanners. Current offset is for  "Top-heading-west" scanner. Can you please specify it in the metadata. Or add the offset for the "Top-heading-east" scanner as well. It should be  [0 , 0 ,0 ]

**Comment by rachelshekar** [comment]
@craig-willis - can this be closed?

**Comment by craig-willis** [comment]
Sorry for the delay, lost track of this ticket.  I've added a sensor identifier to the alignment_correction_offset and update the PR.

**Comment by rachelshekar** [comment]
@ZongyangLi - do you have what you need now?  If so, please close this issue

**Comment by ZongyangLi** [comment]
@rachelshekar I do not have what I need now.

**Comment by rachelshekar** [comment]
dependent upon https://github.com/terraref/reference-data/issues/44

**Comment by rachelshekar** [comment]
Changing this to April milestone since dependent on terraref/computing-pipeline#265 and https://github.com/terraref/reference-data/issues/44

**Comment by rachelshekar** [comment]
Changing to June; #44 still open

**Comment by rachelshekar** [comment]
https://github.com/terraref/sensor-metadata/pull/5
delayed because offset is temperature dependent.  @solmazhajmohammadi will update with additional data.

**Comment by rachelshekar** [comment]
@solmazhajmohammadi please provide an update on the temperature measurements

**Comment by solmazhajmohammadi** [comment]
I uploaded the report here:
[3D_Alignment(2).pdf](https://github.com/terraref/reference-data/files/1145923/3D_Alignment.2.pdf)

**Comment by rachelshekar** [comment]
@solmazhajmohammadi - is this for air or box temperature?

**Comment by rachelshekar** [comment]
- box was not moved when the calibration data was collected
- temperature is air - weather sensor on top of gantry
Does this offset apply for all sensors?
Is the gantry expanding? - eg Is the temperature response different at different ends of the field?

**Comment by rachelshekar** [comment]
Original offset supplied for PR was not correct because temperature plays an important role in the offset.

**Comment by rachelshekar** [comment]
@solmazhajmohammadi - please create new issue for temperature correction and close this issue

**Comment by solmazhajmohammadi** [comment]
@rachelshekar Issue [#63](https://github.com/terraref/reference-data/issues/161)
