### ISSUE TITLE
Standardize how plantcv metadata is stored in Clowder + add to EXIF?

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#88]
In the sample datasets on Clowder the experiment metadata is at the dataset level

![](http://i.imgur.com/gl2y3WF.jpg)

 and genotype is found at the file level way after the exif info 

![](http://i.imgur.com/rvTLEIy.jpg)

Seems like the genotype + barcode + treatment etc should be at the dataset level. 

Would that make sense?

**Comment by nfahlgren** [comment]
@dlebauer or both? But yeah, I agree that those metadata apply down from the dataset level.

It would also be useful to look over MIAPPE and see how it compares to what we have.

**Comment by dlebauer** [comment]
Both works. And perhaps relevant metadata at the collection level too?

MIAPPE is defined here http://cropnet.pl/phenotypes/wp-content/uploads/2016/04/MIAPPE.pdf

Looks like you are the person to provide this information Noah  but @craig-willis may be able to advise on how much we can cover with linked data vs duplication; seems a search should return miappe info + data

**Comment by nfahlgren** [comment]
I need to rework the PlantCV code in the current extractor to analyze the TERRA-REF datasets, based on scripts I got from Todd's group. That would be a good time to incorporate updates to the metadata

**Comment by rachelshekar** [comment]
@max-zilla will look into limitations to EXIF

**Comment by nfahlgren** [comment]
Database extractor: https://github.com/danforthcenter/pheno-data-service

**Comment by rachelshekar** [comment]
Noah wants users to enter experimental data into database and extract that information into EXIF during downstream analysis

**Comment by dlebauer** [comment]
@nfahlgren see https://github.com/terraref/reference-data/issues/137 and contact me if you need assistance.
